version: '3.8'
services:
  adminbarrio-db:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3307:3306'
    container_name: admin_barrio_db
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=adminbarrio_usr
      - MARIADB_DATABASE=adminbarrio_db
    networks:
      - admin_barrio
  adminbarrio_db-app:
    image: docker.io/bitnami/laravel:10
    container_name: admin_barrio_app
    ports:
      - '8000:8000'
    # environment:
    #   APP_NAME: "AdminBarrio"
    #   APP_ENV: "local"
    #   # APP_KEY: "base64:GENERATE_YOUR_OWN_KEY"
    #   APP_DEBUG: "true"
    #   APP_URL: "http://localhost"
    #   LOG_CHANNEL: "stderr"
    #   DB_CONNECTION: "mysql"
    #   DB_HOST: "adminbarrio-db"
    #   DB_PORT: "3306"
    #   DB_DATABASE: "adminbarrio"
    #   DB_USERNAME: "adminbarrrio"
    #   DB_PASSWORD: ""
    #   XDEBUG_MODE: "debug"
    environment:
      - DB_HOST=adminbarrio-db
      - DB_PORT=3306
      - DB_USERNAME=adminbarrio_usr
      - DB_DATABASE=adminbarrio_db
    volumes:
      - './app:/app'
    depends_on:
      - adminbarrio-db
    networks:
      - admin_barrio

networks:
  admin_barrio:
    driver: bridge
