version: "3.9"
services:
  adminbarrio-backend:
    container_name: adminbarrio-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=adminbarrio-db
      - DB_PORT=3306
      - DB_DATABASE=adminbarrio
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - adminbarrio
    ports:
      - "8010:8000"
    depends_on:
      - adminbarrio-db

  adminbarrio-frontend:
    container_name: adminbarrio-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    networks:
      - adminbarrio
    ports:
      - "3011:80"

  adminbarrio-db:
    container_name: adminbarrio-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: adminbarrio
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - adminbarrio
    ports:
      - "3311:3306"

  adminbarrio-mailhog:
    container_name: adminbarrio-mailhog
    image: mailhog/mailhog
    ports:
      - "8026:8025"
    networks:
      - adminbarrio

networks:
  adminbarrio:
    driver: bridge

volumes:
  db-data: